# scripts/precompute_rs3.py
# Usage:
#   conda activate editable-rs3
#   python scripts/precompute_rs3.py data/rs3_sequences.json editable_app/www/rs3_cache.json editable_app/rs3_cache.py

import json, sys, math
from rs3.seq import predict_seq

def sigmoid(x): return 1.0/(1.0+math.exp(-float(x)))

def main(in_json, out_json, out_py):
    seqs = json.load(open(in_json))  # list of 30-mers (uppercase A/C/G/T)
    seqs = [s.upper() for s in seqs]
    raw = predict_seq(seqs, sequence_tracr="Hsu2013")
    scores = [sigmoid(x) for x in raw]
    cache = {s: float(sc) for s, sc in zip(seqs, scores)}

    # Write JSON (for human/CI)
    with open(out_json, "w") as f:
        json.dump(cache, f)
    print(f"[RS3] wrote JSON cache: {out_json} ({len(cache)} items)")

    # Write a Python module (for Pyodide-friendly import)
    with open(out_py, "w") as f:
        f.write("# Auto-generated by precompute_rs3.py\nRS3_CACHE = ")
        json.dump(cache, f)
        f.write("\n")
    print(f"[RS3] wrote Python cache: {out_py}")

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python scripts/precompute_rs3.py <in_json> <out_json> <out_py>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
